# topic: (set in launch file or command line)
deskew: false
max_range: 100.0
min_range: 0.5
voxel_size: 0.4
desired_num_voxelized_points: 3000
planarity_threshold: 0.1
max_points_per_voxel: 3
initial_threshold: 2.0
min_motion_th: 0.01
max_num_iterations: 200
convergence_criterion: 0.0001
