pointcloud_to_laserscan:
  ros__parameters:
    target_frame: base_link
    min_height: -3.0
    max_height: 3.0
    angle_min: -3.14
    angle_max: 3.14
    angle_increment: 0.004
    range_min: 0.1
    range_max: 25.0
    use_inf: true
    inf_epsilon: 1.0
    transform_tolerance: 0.5
    input_topic: /synced_pointcloud
    output_topic: /scan

